version: '3.8'

services:
    app:
        container_name: app-container
        build:
            context: .
            dockerfile: Dockerfile-app
        environment:
            - SUPABASE_URL=https://your-project.supabase.co
            - SUPABASE_ANON_KEY=your-anon-key
        depends_on:
            - vite
        volumes:
            - .:/var/www/html
        ports:
            - "8000:80"

    vite:
        container_name: vite-container
        build:
            context: .
            dockerfile: Dockerfile-vite
        depends_on:
            - app
        ports:
            - "5173:5173"
