services:
    app:
        build:
            context: .
            dockerfile: Dockerfile-app  # Tento Dockerfile pre PHP (Laravel aplikáciu)
        container_name: laravel_app
        ports:
            - "8000:80"  # Laravel bude dostupný na localhost:8000
        volumes:
            - .:/var/www/html
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: ${DB_HOST}  # Pripojenie na Supabase
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_SCHEMA: ${DB_SCHEMA}
            SUPABASE_URL: ${SUPABASE_URL}
            SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
        networks:
            - app_network  # Táto sieť bude automaticky vytvorená Dockerom

networks:
    app_network:  # Definujeme sieť, ale nemusíme špecifikovať driver, ak nevyžaduje konkrétny
        driver: bridge
