FROM node:18

WORKDIR /var/www/html

COPY package*.json ./

RUN npm cache clean --force

RUN rm -rf node_modules package-lock.json && npm install

RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
