version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: reservations-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: reservations_db
            MYSQL_USER: reservations_user
            MYSQL_PASSWORD: reservations_pass
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - mysql_network

volumes:
    mysql_data:

networks:
    mysql_network:
        driver: bridge
